#!/usr/bin/env bash

set -e

[ -n "$(which x11docker)" ] \
    || { echo "x11docker is required https://github.com/mviereck/x11docker"; exit 1; }

[ -n "$(which docker-compose)" ] \
    || { echo "docker-compose is required https://docs.docker.com/compose/install/"; exit 1; }

TAG=${1}
[ -n "${TAG}" ] \
    || { echo "Image tag is required (php, js, cpp)"; exit 1; }

IDE_SCRIPT=${2}
[ -n "${IDE_SCRIPT}" ] \
    || { echo "IDE script is required (~/path/to/ide.sh)"; exit 1; }

IMAGE="01e9/ide:${TAG}"
NETWORK='docker_ide_default'
SCRIPT_DIR=$(dirname $(readlink -f "$0"))

cd ${SCRIPT_DIR}

docker-compose up -d

set +e

x11docker \
    --hostdisplay \
    --home=${HOME} \
    --clipboard \
    --cap-default \
    -- "--cap-add=SYS_PTRACE \
        --network ${NETWORK} \
        --hostname docker-ide" \
    ${IMAGE} \
    sh -c "echo  '██████████████████████████████████' \
        && echo ""█ Container IP http://\\\$(hostname -i) █"" \
        && echo  '██████████████████████████████████' \
        && sleep 3 && exit 1 \
        && ${IDE_SCRIPT}"

docker-compose stop
