#!/usr/bin/env bash

set -e

[ -n "$(which docker-compose)" ] \
    || { echo "docker-compose is recommended https://docs.docker.com/compose/install/"; }

TAG=${1}
[ -n "${TAG}" ] \
    || { echo "Image tag is required (php, js, cpp)"; exit 1; }

IDE_SCRIPT=${2}
[ -n "${IDE_SCRIPT}" ] \
    || { echo "IDE script is required (~/path/to/ide.sh)"; exit 1; }

IMAGE="01e9/ide:${TAG}"
NETWORK='docker_ide_default'
SCRIPT_DIR=$(dirname $(readlink -f "$0"))

shift # TAG
shift # IDE_SCRIPT

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "$(basename $SCRIPT_DIR) <tag> <path-to-ide-exec> [options]"
      echo " "
      echo "options:"
      echo "-h, --help    show brief help"
      echo "-x11docker    pass options to x11docker"
      exit 0
      ;;
    -x11docker)
      shift
      if test $# -gt 0; then
        export X11DOCKER_OPTS="$1"
      else
        echo "no args specified"
        exit 1
      fi
      shift
      ;;
    *)
      break
      ;;
  esac
done

cd ${SCRIPT_DIR}

which docker-compose>/dev/null && docker-compose up -d

set +e

./x11docker \
    --hostdisplay \
    --home=${HOME} \
    --clipboard \
    --cap-default \
    ${X11DOCKER_OPTS} \
    -- "--cap-add=SYS_PTRACE \
        --network ${NETWORK} \
        --hostname docker-ide" \
    ${IMAGE} \
    sh -c "echo '' \
        && echo  '╔════════════════════════════════╗' \
        && echo ""║ Container IP http://\\\$(hostname -i) ║"" \
        && echo  '╚════════════════════════════════╝' \
        && echo '' \
        && ${IDE_SCRIPT}"

which docker-compose>/dev/null && docker-compose stop
