#!/usr/bin/env bash

set -e

[ -n "$(which x11docker)" ] \
    || { echo "x11docker is required"; exit 1; }

[ -n "$(which docker-compose)" ] \
    || { echo "docker-compose is required"; exit 1; }

TAG=${1}
[ -n "${TAG}" ] \
    || { echo "Image tag is required (php, js, cpp)"; exit 1; }

IDE_SCRIPT=${2}
[ -n "${IDE_SCRIPT}" ] \
    || { echo "IDE script is required (~/path/to/ide.sh)"; exit 1; }

IMAGE="01e9/ide:${TAG}"
NETWORK='docker_ide_default'
SCRIPT_DIR=$(dirname $(readlink -f "$0"))

cd ${SCRIPT_DIR}

docker-compose up -d

set +e

x11docker \
    --hostdisplay \
    --homedir ${HOME} \
    --clipboard \
    --stdout --stderr \
    --cap-default \
    -- "--cap-add=SYS_PTRACE \
        -p 80:80 \
        -p 443:443 \
        -p 8080:8080 \
        -p 8443:8443 \
        -p 3000:3000 \
        --network ${NETWORK} \
        --hostname docker-ide" \
    ${IMAGE} ${IDE_SCRIPT}

docker-compose stop
